# Generated by Django 3.0.5 on 2020-04-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='post',
            new_name='project',
        ),
    ]
