# Generated by Django 3.0.5 on 2020-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
